添加简易部署流程[Deployment.md]
running-elephant/datart pull request #359
Opened 2021-12-14 08:56 UTC by zhu-mingye

添加简易部署流程[Deployment.md]  更快上路

2021-12-14 09:13 UTC, xieliuduo commented
👍👍🏻

2021-12-15 10:19 UTC, tianlu-root requested changes
文档完善了很多细节，很赞。关于docker环境的安装部分，建议去掉，这部分不属于datart的安装流程。

2021-12-20 02:30 UTC, zhu-mingye commented
done

2021-12-20 03:58 UTC, tianlu-root approved these changes

2021-12-20 03:58 UTC, merged

2021-12-20 04:05 UTC, scottsut commented
Thanks for the contribution!